### ISSUE TITLE
Task List Issue

### ISSUE THREAD

**Issue by destroylord** [destroylord/Golang-ATM#2]
## Task List

- [x] Kode bank
- [ ] Ubah kode bank
- [x] Saldo awal = 1000.000
- [x] Currency
- [x] Total Saldo
- [x] Informasi Saldo & pengguna
- [ ] Tarik Tunai
- [ ] Biaya admin tarik tunai
- [ ] Minimum tarik saldo
- [ ] List Jumlah tarik tunai
- [ ] Informasi Log tarik tunai
- [ ] Setor Tunai - pecahan 50k & 100k (hitungan Lembaran)
- [ ] Lebih >= 2minute otomatis exit
- [ ] Exit
